# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: ticket_win_development
  username: ticket_win
  host: localhost
  pool: 5
  port: 5432
  
